version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: video-stats-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql_data/:/var/lib/mysql/
        - ./mysql_socks/:/var/run/mysqld/
        - ./mysql_logs:/var/log/mysql/
        - ./mysql_seed:/docker-entrypoint-initdb.d/
      environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
      ports:
        - "7802:3306"
      labels:
        - "traefik.enable=false"
      networks:
        - okstatslocal

    webserver:
      image: nginx:alpine
      container_name: video-stats-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - "7800:80"
          - "5580:80"
      networks:
          - web
          - okstatslocal
      depends_on:
          - php-fpm
      labels:
          - "traefik.docker.network=web"
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:ok-videostats.hopto.org"
          - "traefik.port=80"
          - "traefik.protocol=http"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: video-stats-php-fpm
      working_dir: /application
      labels:
        - "traefik.enable=false"
      networks:
        - okstatslocal
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

networks:
  web:
    external: true
  okstatslocal:
    external: false
